project:
  type: website
  output-dir: docs
  
book:
  title: "Stella Cometta Febriana"
  subtitle: "Portfolio Asesmen II-2100 KIPP"
  author: "18224035 Stella Cometta Febriana"
  date: "9/15/2025"
  chapters:
    - index.qmd
    - All_About_me/index.qmd
    - My_Song_for_You/index.qmd
    - My_Stories_for_You/index.qmd
    - My_Shapes/index.qmd
    - My_Personal_Reviews/index.qmd
    - My_Concepts/index.qmd
    - My_Opinions/index.qmd
    - My_Innovations/index.qmd
    - My_Knowledge/index.qmd
    - My_Professional_Reviews/index.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

website:
  title: "Portofolio-UTS-18224035"
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



