name: Quarto Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "quarto-publish"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # (Opsional) bekukan eksekusi agar code-cells tidak dieksekusi di CI
      # dan gunakan hasil local render yang tersimpan di _freeze
      # - run: echo "execute:\n  freeze: auto" >> _quarto.yml

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2

      - name: Upload artifact ke Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy ke GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
